export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const CHANGE_ACTIVE_BOARD = "CHANGE_ACTIVE_BOARD";

export const SET_START = "SET_START";
export const SET_START_TODOS = "SET_START_TODOS";

export const NEW_BOARD_SUCCESS = "NEW_BOARD_SUCCESS";
export const NEW_BOARD_FAIL = "NEW_BOARD_FAIL";

export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const FETCH_BOARDS_FAIL = "FETCH_BOARDS_FAIL";

export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL";

export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL";

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAIL = "ADD_TODO_FAIL";

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";

export const CHECK_TODO_SUCCESS = "CHECK_TODO_SUCCESS";
export const CHECK_TODO_FAIL = "CHECK_TODO_FAIL";
